// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: infer_contact.proto
#ifndef GRPC_infer_5fcontact_2eproto__INCLUDED
#define GRPC_infer_5fcontact_2eproto__INCLUDED

#include "infer_contact.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace InferContact {

class InferContactGrpc final {
 public:
  static constexpr char const* service_full_name() {
    return "InferContact.InferContactGrpc";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status cmd_node(::grpc::ClientContext* context, const ::InferContact::data& request, ::InferContact::data* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InferContact::data>> Asynccmd_node(::grpc::ClientContext* context, const ::InferContact::data& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InferContact::data>>(Asynccmd_nodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InferContact::data>> PrepareAsynccmd_node(::grpc::ClientContext* context, const ::InferContact::data& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InferContact::data>>(PrepareAsynccmd_nodeRaw(context, request, cq));
    }
    virtual ::grpc::Status ai_init(::grpc::ClientContext* context, const ::InferContact::data& request, ::InferContact::data* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InferContact::data>> Asyncai_init(::grpc::ClientContext* context, const ::InferContact::data& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InferContact::data>>(Asyncai_initRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InferContact::data>> PrepareAsyncai_init(::grpc::ClientContext* context, const ::InferContact::data& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InferContact::data>>(PrepareAsyncai_initRaw(context, request, cq));
    }
    virtual ::grpc::Status unload(::grpc::ClientContext* context, const ::InferContact::data& request, ::InferContact::data* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InferContact::data>> Asyncunload(::grpc::ClientContext* context, const ::InferContact::data& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InferContact::data>>(AsyncunloadRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InferContact::data>> PrepareAsyncunload(::grpc::ClientContext* context, const ::InferContact::data& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::InferContact::data>>(PrepareAsyncunloadRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void cmd_node(::grpc::ClientContext* context, const ::InferContact::data* request, ::InferContact::data* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void cmd_node(::grpc::ClientContext* context, const ::InferContact::data* request, ::InferContact::data* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void cmd_node(::grpc::ClientContext* context, const ::InferContact::data* request, ::InferContact::data* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void ai_init(::grpc::ClientContext* context, const ::InferContact::data* request, ::InferContact::data* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void ai_init(::grpc::ClientContext* context, const ::InferContact::data* request, ::InferContact::data* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void ai_init(::grpc::ClientContext* context, const ::InferContact::data* request, ::InferContact::data* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void unload(::grpc::ClientContext* context, const ::InferContact::data* request, ::InferContact::data* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void unload(::grpc::ClientContext* context, const ::InferContact::data* request, ::InferContact::data* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void unload(::grpc::ClientContext* context, const ::InferContact::data* request, ::InferContact::data* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InferContact::data>* Asynccmd_nodeRaw(::grpc::ClientContext* context, const ::InferContact::data& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InferContact::data>* PrepareAsynccmd_nodeRaw(::grpc::ClientContext* context, const ::InferContact::data& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InferContact::data>* Asyncai_initRaw(::grpc::ClientContext* context, const ::InferContact::data& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InferContact::data>* PrepareAsyncai_initRaw(::grpc::ClientContext* context, const ::InferContact::data& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InferContact::data>* AsyncunloadRaw(::grpc::ClientContext* context, const ::InferContact::data& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::InferContact::data>* PrepareAsyncunloadRaw(::grpc::ClientContext* context, const ::InferContact::data& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status cmd_node(::grpc::ClientContext* context, const ::InferContact::data& request, ::InferContact::data* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InferContact::data>> Asynccmd_node(::grpc::ClientContext* context, const ::InferContact::data& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InferContact::data>>(Asynccmd_nodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InferContact::data>> PrepareAsynccmd_node(::grpc::ClientContext* context, const ::InferContact::data& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InferContact::data>>(PrepareAsynccmd_nodeRaw(context, request, cq));
    }
    ::grpc::Status ai_init(::grpc::ClientContext* context, const ::InferContact::data& request, ::InferContact::data* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InferContact::data>> Asyncai_init(::grpc::ClientContext* context, const ::InferContact::data& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InferContact::data>>(Asyncai_initRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InferContact::data>> PrepareAsyncai_init(::grpc::ClientContext* context, const ::InferContact::data& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InferContact::data>>(PrepareAsyncai_initRaw(context, request, cq));
    }
    ::grpc::Status unload(::grpc::ClientContext* context, const ::InferContact::data& request, ::InferContact::data* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InferContact::data>> Asyncunload(::grpc::ClientContext* context, const ::InferContact::data& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InferContact::data>>(AsyncunloadRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InferContact::data>> PrepareAsyncunload(::grpc::ClientContext* context, const ::InferContact::data& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::InferContact::data>>(PrepareAsyncunloadRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void cmd_node(::grpc::ClientContext* context, const ::InferContact::data* request, ::InferContact::data* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void cmd_node(::grpc::ClientContext* context, const ::InferContact::data* request, ::InferContact::data* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void cmd_node(::grpc::ClientContext* context, const ::InferContact::data* request, ::InferContact::data* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void ai_init(::grpc::ClientContext* context, const ::InferContact::data* request, ::InferContact::data* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void ai_init(::grpc::ClientContext* context, const ::InferContact::data* request, ::InferContact::data* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void ai_init(::grpc::ClientContext* context, const ::InferContact::data* request, ::InferContact::data* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void unload(::grpc::ClientContext* context, const ::InferContact::data* request, ::InferContact::data* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void unload(::grpc::ClientContext* context, const ::InferContact::data* request, ::InferContact::data* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void unload(::grpc::ClientContext* context, const ::InferContact::data* request, ::InferContact::data* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::InferContact::data>* Asynccmd_nodeRaw(::grpc::ClientContext* context, const ::InferContact::data& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::InferContact::data>* PrepareAsynccmd_nodeRaw(::grpc::ClientContext* context, const ::InferContact::data& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::InferContact::data>* Asyncai_initRaw(::grpc::ClientContext* context, const ::InferContact::data& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::InferContact::data>* PrepareAsyncai_initRaw(::grpc::ClientContext* context, const ::InferContact::data& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::InferContact::data>* AsyncunloadRaw(::grpc::ClientContext* context, const ::InferContact::data& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::InferContact::data>* PrepareAsyncunloadRaw(::grpc::ClientContext* context, const ::InferContact::data& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_cmd_node_;
    const ::grpc::internal::RpcMethod rpcmethod_ai_init_;
    const ::grpc::internal::RpcMethod rpcmethod_unload_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status cmd_node(::grpc::ServerContext* context, const ::InferContact::data* request, ::InferContact::data* response);
    virtual ::grpc::Status ai_init(::grpc::ServerContext* context, const ::InferContact::data* request, ::InferContact::data* response);
    virtual ::grpc::Status unload(::grpc::ServerContext* context, const ::InferContact::data* request, ::InferContact::data* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_cmd_node : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_cmd_node() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_cmd_node() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status cmd_node(::grpc::ServerContext* /*context*/, const ::InferContact::data* /*request*/, ::InferContact::data* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestcmd_node(::grpc::ServerContext* context, ::InferContact::data* request, ::grpc::ServerAsyncResponseWriter< ::InferContact::data>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ai_init : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ai_init() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ai_init() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ai_init(::grpc::ServerContext* /*context*/, const ::InferContact::data* /*request*/, ::InferContact::data* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestai_init(::grpc::ServerContext* context, ::InferContact::data* request, ::grpc::ServerAsyncResponseWriter< ::InferContact::data>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_unload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_unload() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_unload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status unload(::grpc::ServerContext* /*context*/, const ::InferContact::data* /*request*/, ::InferContact::data* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestunload(::grpc::ServerContext* context, ::InferContact::data* request, ::grpc::ServerAsyncResponseWriter< ::InferContact::data>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_cmd_node<WithAsyncMethod_ai_init<WithAsyncMethod_unload<Service > > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_cmd_node : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_cmd_node() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::InferContact::data, ::InferContact::data>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::InferContact::data* request, ::InferContact::data* response) { return this->cmd_node(context, request, response); }));}
    void SetMessageAllocatorFor_cmd_node(
        ::grpc::experimental::MessageAllocator< ::InferContact::data, ::InferContact::data>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::InferContact::data, ::InferContact::data>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_cmd_node() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status cmd_node(::grpc::ServerContext* /*context*/, const ::InferContact::data* /*request*/, ::InferContact::data* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* cmd_node(
      ::grpc::CallbackServerContext* /*context*/, const ::InferContact::data* /*request*/, ::InferContact::data* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* cmd_node(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::InferContact::data* /*request*/, ::InferContact::data* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_ai_init : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_ai_init() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::InferContact::data, ::InferContact::data>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::InferContact::data* request, ::InferContact::data* response) { return this->ai_init(context, request, response); }));}
    void SetMessageAllocatorFor_ai_init(
        ::grpc::experimental::MessageAllocator< ::InferContact::data, ::InferContact::data>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::InferContact::data, ::InferContact::data>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_ai_init() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ai_init(::grpc::ServerContext* /*context*/, const ::InferContact::data* /*request*/, ::InferContact::data* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* ai_init(
      ::grpc::CallbackServerContext* /*context*/, const ::InferContact::data* /*request*/, ::InferContact::data* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* ai_init(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::InferContact::data* /*request*/, ::InferContact::data* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_unload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_unload() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::InferContact::data, ::InferContact::data>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::InferContact::data* request, ::InferContact::data* response) { return this->unload(context, request, response); }));}
    void SetMessageAllocatorFor_unload(
        ::grpc::experimental::MessageAllocator< ::InferContact::data, ::InferContact::data>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(2);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::InferContact::data, ::InferContact::data>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_unload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status unload(::grpc::ServerContext* /*context*/, const ::InferContact::data* /*request*/, ::InferContact::data* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* unload(
      ::grpc::CallbackServerContext* /*context*/, const ::InferContact::data* /*request*/, ::InferContact::data* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* unload(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::InferContact::data* /*request*/, ::InferContact::data* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_cmd_node<ExperimentalWithCallbackMethod_ai_init<ExperimentalWithCallbackMethod_unload<Service > > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_cmd_node<ExperimentalWithCallbackMethod_ai_init<ExperimentalWithCallbackMethod_unload<Service > > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_cmd_node : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_cmd_node() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_cmd_node() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status cmd_node(::grpc::ServerContext* /*context*/, const ::InferContact::data* /*request*/, ::InferContact::data* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ai_init : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ai_init() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ai_init() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ai_init(::grpc::ServerContext* /*context*/, const ::InferContact::data* /*request*/, ::InferContact::data* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_unload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_unload() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_unload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status unload(::grpc::ServerContext* /*context*/, const ::InferContact::data* /*request*/, ::InferContact::data* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_cmd_node : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_cmd_node() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_cmd_node() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status cmd_node(::grpc::ServerContext* /*context*/, const ::InferContact::data* /*request*/, ::InferContact::data* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestcmd_node(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ai_init : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ai_init() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ai_init() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ai_init(::grpc::ServerContext* /*context*/, const ::InferContact::data* /*request*/, ::InferContact::data* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestai_init(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_unload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_unload() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_unload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status unload(::grpc::ServerContext* /*context*/, const ::InferContact::data* /*request*/, ::InferContact::data* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestunload(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_cmd_node : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_cmd_node() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->cmd_node(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_cmd_node() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status cmd_node(::grpc::ServerContext* /*context*/, const ::InferContact::data* /*request*/, ::InferContact::data* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* cmd_node(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* cmd_node(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_ai_init : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_ai_init() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ai_init(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_ai_init() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ai_init(::grpc::ServerContext* /*context*/, const ::InferContact::data* /*request*/, ::InferContact::data* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* ai_init(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* ai_init(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_unload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_unload() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->unload(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_unload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status unload(::grpc::ServerContext* /*context*/, const ::InferContact::data* /*request*/, ::InferContact::data* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* unload(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* unload(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_cmd_node : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_cmd_node() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::InferContact::data, ::InferContact::data>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::InferContact::data, ::InferContact::data>* streamer) {
                       return this->Streamedcmd_node(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_cmd_node() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status cmd_node(::grpc::ServerContext* /*context*/, const ::InferContact::data* /*request*/, ::InferContact::data* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedcmd_node(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::InferContact::data,::InferContact::data>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ai_init : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ai_init() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::InferContact::data, ::InferContact::data>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::InferContact::data, ::InferContact::data>* streamer) {
                       return this->Streamedai_init(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ai_init() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ai_init(::grpc::ServerContext* /*context*/, const ::InferContact::data* /*request*/, ::InferContact::data* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedai_init(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::InferContact::data,::InferContact::data>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_unload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_unload() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::InferContact::data, ::InferContact::data>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::InferContact::data, ::InferContact::data>* streamer) {
                       return this->Streamedunload(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_unload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status unload(::grpc::ServerContext* /*context*/, const ::InferContact::data* /*request*/, ::InferContact::data* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedunload(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::InferContact::data,::InferContact::data>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_cmd_node<WithStreamedUnaryMethod_ai_init<WithStreamedUnaryMethod_unload<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_cmd_node<WithStreamedUnaryMethod_ai_init<WithStreamedUnaryMethod_unload<Service > > > StreamedService;
};

}  // namespace InferContact


#endif  // GRPC_infer_5fcontact_2eproto__INCLUDED
